# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2016-2018, JFrog
# This file is distributed under the same license as the conan package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: conan 1.9\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-09-15 10:14+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh_TW\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../../integrations/makefile.rst:5
msgid "Autotools: configure/make"
msgstr ""

#: ../../../integrations/makefile.rst:7
msgid ""
"If you are using **configure**/**make** you can use "
"**AutoToolsBuildEnvironment** helper. This helper sets ``LIBS``, "
"``LDFLAGS``, ``CFLAGS``, ``CXXFLAGS`` and ``CPPFLAGS`` environment variables "
"based on your requirements."
msgstr ""

#: ../../../integrations/makefile.rst:10
msgid ""
"Check :ref:`Building with Autotools <autotools_reference>` for more info."
msgstr ""
