# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2016-2024, JFrog
# This file is distributed under the same license as the conan package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: conan 2.6\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-09-15 14:33+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh_TW\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../../integrations/makefile.rst:4
msgid "|gnu_make_logo| Makefile"
msgstr ""

#: ../../../integrations/makefile.rst:22
msgid "gnu_make_logo"
msgstr ""

#: ../../../integrations/makefile.rst:6
msgid ""
"Conan provides different tools to help manage your projects using Make. They "
"can be imported from ``conan.tools.gnu``. Besides the most popular variant, "
"GNU Make, Conan also supports other variants like BSD Make. The most "
"relevant tools are:"
msgstr ""

#: ../../../integrations/makefile.rst:10
msgid ""
"`MakeDeps`: the dependencies generator for Make, which generates a Makefile "
"containing definitions that the Make build tool can understand."
msgstr ""

#: ../../../integrations/makefile.rst:13
msgid ""
"Currently, there is no ``MakeToolchain`` generator, it should be added in "
"the future."
msgstr ""

#: ../../../integrations/makefile.rst:15
msgid ""
"For the full list of tools under ``conan.tools.gnu`` please check the :ref:"
"`reference <conan_tools_gnu>` section."
msgstr ""

#: ../../../integrations/makefile.rst:20
msgid "Reference for :ref:`MakeDeps<conan_tools_gnu_makedeps>`."
msgstr ""
